version: '3.7'
services:

  db:
    image: mysql:8.0
    
    container_name: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - 3308:3306
   
  app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '9000:80'
      environment:
        PMA_HOST: db

      
